### ISSUE TITLE
[Discussion] Current custom styles break shell-theme compatibility

### ISSUE THREAD

**Issue by IBA4** [Biplab-Dutta/Nepali_Date#1]
The current Label stylesheet uses font-color: white, fixed font size and uses padding to center the vertical alignment.
I didn't create a pull request with my changes on this commit on my fork: https://github.com/IBA4/Nepali_Date/commit/ada9a4d941d5c7b0f9bc9098e941bd2d495c5afb because this contains a new import and `|  ` is removed.

**Comment by Biplab-Dutta** [comment]
@IBA4 Thanks for your fork. The fact that I don't excel in GJS made me do it in such a way 😅. Clutter is a better option to centralize the date. Can you also add a separator `|` in a dynamic way while using Clutter?

**Comment by IBA4** [comment]
@Biplab-Dutta I think creating a preference menu and giving the user choice will make it easier to decide which side the separator could be placed (or not at all). I use Dash-to-panel to theme the panel so my alignment is not centered and such might be the case for others too. I am not so good at GJS too. So, it will take some time. Meanwhile, you could keep `| ` as is and reflect other changes from my fork.

**Comment by Biplab-Dutta** [comment]
@IBA4 I pushed new code with clutter implemented along with the separator `|`. For now, you can customize the extension that suits you on your local machine. I will definitely consider your suggestion regarding user choice but it will take some time to implement as I have a tight schedule.
Again, thanks for the fork.
