### ISSUE TITLE
Add gnome 47 compatibility

### ISSUE THREAD

**Issue by GrishmaKhanal** [Biplab-Dutta/Nepali_Date#10]
There seems to be a pull request for gnome 47, hope you can make time to add gnome-47 compatibility

**Comment by Biplab-Dutta** [comment]
Hi.
Yes, I am aware of it. I plan on checking that PR after Tihar as I am on my holiday at the moment.
Thanks for your patience.

**Comment by Biplab-Dutta** [comment]
The PR regarding Gnome 47 support has been merged in the master branch. You will receive an update for the extension soon. Thanks for using the extension.
Closing this issue as completed.
