### ISSUE TITLE
Issue with New Year 2079

### ISSUE THREAD

**Issue by metalaarif** [Biplab-Dutta/Nepali_Date#2]
Hi, 

Today is Happy New Year 2079 but it's not working - it is currently displaying "undefined 1, 2078 B.S."

Can you please fix the issue?

**Comment by metalaarif** [comment]
I just got an update but now - I'm getting "Error".

**Comment by Biplab-Dutta** [comment]
Hello. Thanks for raising an issue. I believe you must have gotten an extension update by now where it should be working as expected.
