### ISSUE TITLE
Not compatible with Gnome 43

### ISSUE THREAD

**Issue by sulavmhrzn** [Biplab-Dutta/Nepali_Date#5]
I absolutely love this extension, but with the recent major release to Gnome, the extension seems to be incompatible with it.

**Comment by Biplab-Dutta** [comment]
Hi @sulavmhrzn. Thanks for letting me know. Would you mind checking again if the extension is working or not? I have sent an update. Let me know what the result is.

**Comment by sulavmhrzn** [comment]
Thank you @Biplab-Dutta, It is now working perfectly. Cheers!
