### ISSUE TITLE
How to remove (B.S.) ?

### ISSUE THREAD

**Issue by herp1derp2** [Biplab-Dutta/Nepali_Date#7]
I removed it from extension.js but it still show on titlebar after refresh/re-login. 

Hey, i rebooted and it's gone now. ^^;

**Comment by Biplab-Dutta** [comment]
@herp1derp2 Thanks for installing the extension.
To remove `B.S.` from the title bar, navigate to `~/.local/share/gnome-shell/extensions/nepali-date@biplab` and then edit `extension.js`.
Then save your changes.
Then logout and log back in. That should work.
