### ISSUE TITLE
Add gnome 46 compatibility

### ISSUE THREAD

**Issue by SiddhantSilwal** [Biplab-Dutta/Nepali_Date#8]

**Comment by Biplab-Dutta** [comment]
Hi. I will look into it once I get some time. Thanks for raising an issue.
Shall keep it open until I fix it.

**Comment by Biplab-Dutta** [comment]
Hi @SiddhantSilwal. The extension has been updated to support Gnome 46. You should find the update anytime soon. Thanks for opening this issue.
Closing it as completed.
